Initial commit of a potential bug with generated code and add_custom_command
The first build on windows fails because the moc_foo.cxx file isn't generated.
The ui_foo.h and bar.h are correctly generated however.
On the second build, or whenever bar.h and or ui_foo.h are present, the
project builds fine.

Note the missing "Generating moc_foo.cxx" in the build output of the first pass:

1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>  Checking Build System
1>  CMake does not need to re-run because W:/Jungle/CMakePlayground/LibBug_build/CMakeFiles/generate.stamp is up-to-date.
2>------ Build started: Project: bar_generator, Configuration: Debug x64 ------
2>  Building Custom Rule W:/Jungle/CMakePlayground/LibBug/CMakeLists.txt
2>  CMake does not need to re-run because W:\Jungle\CMakePlayground\LibBug_build\CMakeFiles\generate.stamp is up-to-date.
2>  bar_generator.cxx
2>  bar_generator.vcxproj -> W:\Jungle\CMakePlayground\LibBug_build\Debug\bar_generator.exe
3>------ Build started: Project: foo, Configuration: Debug x64 ------
3>  Building Custom Rule W:/Jungle/CMakePlayground/LibBug/CMakeLists.txt
3>  CMake does not need to re-run because W:\Jungle\CMakePlayground\LibBug_build\CMakeFiles\generate.stamp is up-to-date.
3>  Generating ui_foo.h
3>  Generating bar.h
3>  moc_foo.cxx
3>c1xx : fatal error C1083: Cannot open source file: 'W:\Jungle\CMakePlayground\LibBug_build\moc_foo.cxx': No such file or directory
4>------ Skipped Build: Project: ALL_BUILD, Configuration: Debug x64 ------
4>Project not selected to build for this solution configuration
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 1 skipped ==========

And its presence in the 2nd build:

1>------ Build started: Project: foo, Configuration: Debug x64 ------
1>  Generating moc_foo.cxx
1>  moc_foo.cxx
1>  foo.vcxproj -> W:\Jungle\CMakePlayground\LibBug_build\Debug\foo.lib
2>------ Skipped Build: Project: ALL_BUILD, Configuration: Debug x64 ------
2>Project not selected to build for this solution configuration
========== Build: 1 succeeded, 0 failed, 2 up-to-date, 1 skipped ==========